# https://docs.openstack.org/mitaka/install-guide-obs/launch-instance-heat.html
heat_template_version: 2016-10-14

description: >
  Simple template to deploy 2x core CPU 2G RAM  
  ubuntu 18.04 LTS	

parameters:
  network_id:
    label: Network ID
    type: string
    description: Network ID to use for the instance	
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  instance_type:
    type: string
    label: Instance Flavor Type
    description: Type of instance (flavor) to be used    
  security_group:
    type: string
    label: Security groups
    description: Security group to be used 
        								  
resources:                              
  instance:                             
    type: OS::Nova::Server              
    properties:                         
      # flavor: 2_CPU.2GB_RAM  
      flavor: { get_param: instance_type }              
      # image: Ulakbim Ubuntu Server 18.04.LTS Cloud
      image: { get_param: image_id }
      networks:                         
        # - network: bak_net
        - network: { get_param: network_id }              
      # key_name: cloud-key
      key_name: { get_param: key_name }
      security_groups: { get_param: image_id }
        # - ubuntusecgrp
        
outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ instance, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ instance, first_address ] }  
         