# https://docs.openstack.org/mitaka/install-guide-obs/launch-instance-heat.html
# heat_template_version: 2015-04-30 
heat_template_version: 2016-10-14

description: >
  Template with a seperate environments yamls file,

parameters:
  network_id:
    label: Network ID
    type: string
    description: Network ID to use for the instance
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  instance_name:
    type: string
    description: Name of the instance.    
  instance_type:
    type: string
    label: Instance Flavor Type
    description: Type of instance (flavor) to be used    
  security_group:
    type: string
    label: Security groups
    description: Security group to be used  

resources:
  myindexedgroup:
   type: OS::Heat::ResourceGroup
   properties:
    count: 2
    resource_def:
     type: OS::Nova::Server
     properties:
      name: ubuntu2004_%index%
      flavor: { get_param: instance_type }   
      image: { get_param: image_id }
      networks:                         
        - network: { get_param: network_id } 
      key_name: { get_param: key_name }
      security_groups: [ubuntusecgrp]
      user_data: |
        #!/bin/sh
        hostnamectl status"   

