# https://docs.openstack.org/mitaka/install-guide-obs/launch-instance-heat.html
# heat_template_version: 2015-04-30 
heat_template_version: 2016-10-14

description: >
  Simple nested template to deploy 2x core CPU 2G RAM  
  ubuntu 20.04 LTS	cluster


resources:

  ubuntu2004_cluster_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server
        properties:
          name: ubuntusrv_%index%
          image: "ubuntu-trusty-x86_64"
          flavor: 2_CPU.2GB_RAM  
          networks:                         
            - network: ubuntu_net
          floating-network-id:
              type: string
              label: Floating Network ID
              description: UUID of the external network. The private network created by this stack will route to this network. Any floating IP addresses needed by this stack will also route to this network. 
  minion-count-elk:              
          key_name: ubuntu_keys
          security_groups:
            - ubuntusecgrp         